services:
  - type: worker
    name: tg-security-bot
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: VIRUSTOTAL_API_KEY
        sync: false
      - key: HIBP_API_KEY
        sync: false
